# Run: sfb sweep -c configs/copy_all_models.yaml

task: copy
sequence_length: [64,128,256,512]
vocabulary_size: [64,128,256]
loss: [
  #shift_tolerant_ce,
  cross_entropy]
target_noise: [0.0, 0.1]
batch_size: 128
steps: 5000
eval_every: 1000
seed: 42

models:
  - model: simple_nn
    d_model: 64

  - model: gru
    d_model: 64
    n_layers: 1

  - model: lstm
    d_model: 64
    n_layers: 1

  - model: bigru
    d_model: 64
    n_layers: 1

  # - model: s4d
  #   d_model: 64
  #   n_layers: 4

  - model: transformer
    d_model: 64
    n_layers: 4
    n_heads: 4

  - model: autoencoder
    d_model: 64
    n_layers: 2
    bottleneck_dim: 32
